/*
 *   Copyright (c) 2025 @wxiwxi
 *   All rights reserved.
 *   个人练习项目，作者@wxiwxi，供学习参考。
 */
import * as locales from './i18n/locales'
export * from './api/exporters/html/externalHTMLExporter'
export * from './api/exporters/html/internalHTMLSerializer'
export * from './api/getBlockInfoFromPos'
export * from './api/testUtil'
export * from './blocks/AudioBlockContent/AudioBlockContent'
export * from './blocks/CodeBlockContent/CodeBlockContent'
export * from './blocks/defaultBlockHelpers'
export * from './blocks/defaultBlocks'
export * from './blocks/defaultBlockTypeGuards'
export * from './blocks/defaultProps'
export * from './blocks/FileBlockContent/FileBlockContent'
export * from './blocks/FileBlockContent/fileBlockHelpers'
export * from './blocks/FileBlockContent/uploadToTmpFilesDotOrg_DEV_ONLY'
export * from './blocks/ImageBlockContent/ImageBlockContent'
export { parseImageElement } from './blocks/ImageBlockContent/imageBlockHelpers'
export { EMPTY_CELL_HEIGHT, EMPTY_CELL_WIDTH } from './blocks/TableBlockContent/TableExtension'
export * from './blocks/VideoBlockContent/VideoBlockContent'
export * from './editor/WangxDocEditor'
export * from './editor/WangxDocExtensions'
export * from './editor/WangxDocSchema'
export * from './editor/selectionTypes'
export * from './extensions-shared/UiElementPosition'
export * from './extensions/FilePanel/FilePanelPlugin'
export * from './extensions/FormattingToolbar/FormattingToolbarPlugin'
export * from './extensions/LinkToolbar/LinkToolbarPlugin'
export * from './extensions/SideMenu/SideMenuPlugin'
export * from './extensions/SuggestionMenu/DefaultGridSuggestionItem'
export * from './extensions/SuggestionMenu/DefaultSuggestionItem'
export * from './extensions/SuggestionMenu/getDefaultEmojiPickerItems'
export * from './extensions/SuggestionMenu/getDefaultSlashMenuItems'
export * from './extensions/SuggestionMenu/SuggestionPlugin'
export * from './extensions/TableHandles/TableHandlesPlugin'
export * from './schema'
export * from './i18n/dictionary'
export * from './util/browser'
export * from './util/esmDependencies'
export * from './util/string'
export * from './util/typescript'
export { UnreachableCaseError, assertEmpty } from './util/typescript'
export { locales }

// for testing from react (TODO: move):
export * from './api/nodeConversions/blockToNode'
export * from './api/nodeConversions/nodeToBlock'
export * from './api/testUtil/partialBlockTestUtil'
export * from './extensions/UniqueID/UniqueID'

// for server-util (TODO: maybe move):
export * from './api/exporters/markdown/markdownExporter'
export * from './api/parsers/html/parseHTML'
export * from './api/parsers/markdown/parseMarkdown'
